Fix variables in on boot script

diff --git a/install b/install
--- a/install
+++ b/install
@@ -48,28 +48,26 @@ cat << EOF
 #!/usr/bin/env bash
 
 WG_INTERFACE="wg0"
-WIREGUARD_PATH=""
+
+
 if [ -d "/data/wireguard" ]; then
-  WIREGUARD_PATH="/data/wireguard"
+  [[ -x "/data/wireguard/setup_wireguard.sh" ]] && "\${WIREGUARD_PATH}/setup_wireguard.sh" >&2
 elif [ -d "/mnt/data/wireguard" ]; then
-  WIREGUARD_PATH="/mnt/data/wireguard"
+  [[ -x "/mnt/data/wireguard/setup_wireguard.sh" ]] && "\${WIREGUARD_PATH}/setup_wireguard.sh" >&2
 else
   exit 1
 fi
 
-[[ -x "${WIREGUARD_PATH}/setup_wireguard.sh" ]] && "${WIREGUARD_PATH}/setup_wireguard.sh" >&2
-
-if [[ -n "$(command -v wg-quick)" ]]; then
-  echo "wg-quick up ${WG_INTERFACE}"
-  wg-quick up ${WG_INTERFACE}
+if [[ -n "/usr/bin/wg-quick" ]]; then
+  /usr/bin/wg-quick up "\$WG_INTERFACE"
 else
   # You can add whatever here like a telegram script to notify that wg could not start
-  echo "Wireguard could not be started $(date +%s)" >> /var/log/wg-startup.log
+  echo "Wireguard could not be started \$(date +%s)" >> /var/log/wg-startup.log
 EOF
 }
 
 echo "Downloading wireguard-kmod"
-curl -LJo "$TMP_WIREGUARD_FILE" "$(get_latest_download_url)"
+curl -sLJo "$TMP_WIREGUARD_FILE" "$(get_latest_download_url)"
 sleep 1
 
 if [ ! -f "$TMP_WIREGUARD_FILE" ]; then
@@ -77,8 +75,8 @@ if [ ! -f "$TMP_WIREGUARD_FILE" ]; then
   exit 4
 fi
 
-echo "Unzipping"
-tar -C "$(get_persistent_path)" -xvzf "$TMP_WIREGUARD_FILE"
+echo "Unzipping wireguard-kmod"
+tar -C "$(get_persistent_path)" -xzf "$TMP_WIREGUARD_FILE"
 sleep 1
 
 if [ ! -d "$(get_persistent_path "wireguard")" ]; then
